# Generated by Django 3.1.7 on 2021-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudmysqldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'employes',
            },
        ),
    ]
