# Generated by Django 3.1.7 on 2021-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudmysqldb', '0002_employes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='salt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
