# Generated by Django 3.1.7 on 2021-03-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmysqldb', '0003_employes_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='salt',
        ),
    ]
